//! Auto-generated registry data for unit metadata.
//!
//! This module contains the scale constants and registry match arms for all units.

use core::f64::consts::PI;

// Precomputed constants for complex expressions
const METERS_PER_LIGHT_YEAR: f64 = 9_460_730_472_580_800.0; // 299_792_458.0 * 86_400.0 * 365.25
const METERS_PER_PARSEC: f64 = 30_856_775_814_913_672.8; // 149_597_870_700.0 * 648_000.0 / PI
const SECONDS_PER_DAY: f64 = 86_400.0;
const SECONDS_PER_YEAR: f64 = 31_556_952.0; // 365.2425 * 86_400.0
const SECONDS_PER_JULIAN_YEAR: f64 = 31_557_600.0; // 365.25 * 86_400.0

/// Macro to generate registry metadata entries
macro_rules! define_registry_entries {
    () => {
        $crate::registry_match_arms![
            // Length units (canonical: Meter = 1.0)
            (Meter, Length, 1.0, "Meter"),
            (Yoctometer, Length, 1e-24, "Yoctometer"),
            (Zeptometer, Length, 1e-21, "Zeptometer"),
            (Attometer, Length, 1e-18, "Attometer"),
            (Femtometer, Length, 1e-15, "Femtometer"),
            (Picometer, Length, 1e-12, "Picometer"),
            (Nanometer, Length, 1e-9, "Nanometer"),
            (Micrometer, Length, 1e-6, "Micrometer"),
            (Millimeter, Length, 1e-3, "Millimeter"),
            (Centimeter, Length, 1e-2, "Centimeter"),
            (Decimeter, Length, 1e-1, "Decimeter"),
            (Decameter, Length, 1e1, "Decameter"),
            (Hectometer, Length, 1e2, "Hectometer"),
            (Kilometer, Length, 1_000.0, "Kilometer"),
            (Megameter, Length, 1e6, "Megameter"),
            (Gigameter, Length, 1e9, "Gigameter"),
            (Terameter, Length, 1e12, "Terameter"),
            (Petameter, Length, 1e15, "Petameter"),
            (Exameter, Length, 1e18, "Exameter"),
            (Zettameter, Length, 1e21, "Zettameter"),
            (Yottameter, Length, 1e24, "Yottameter"),
            (AstronomicalUnit, Length, 149_597_870_700.0, "AstronomicalUnit"),
            (LightYear, Length, METERS_PER_LIGHT_YEAR, "LightYear"),
            (Parsec, Length, METERS_PER_PARSEC, "Parsec"),
            (Kiloparsec, Length, METERS_PER_PARSEC * 1_000.0, "Kiloparsec"),
            (Megaparsec, Length, METERS_PER_PARSEC * 1_000_000.0, "Megaparsec"),
            (Gigaparsec, Length, METERS_PER_PARSEC * 1_000_000_000.0, "Gigaparsec"),
            (Inch, Length, 0.0254, "Inch"),
            (Foot, Length, 0.3048, "Foot"),
            (Yard, Length, 0.9144, "Yard"),
            (Mile, Length, 1_609.344, "Mile"),
            (NauticalMile, Length, 1_852.0, "NauticalMile"),
            (Chain, Length, 20.1168, "Chain"),
            (Rod, Length, 5.0292, "Rod"),
            (Link, Length, 0.201168, "Link"),
            (Fathom, Length, 1.8288, "Fathom"),
            (EarthMeridionalCircumference, Length, 40_007_863.0, "EarthMeridionalCircumference"),
            (EarthEquatorialCircumference, Length, 40_075_017.0, "EarthEquatorialCircumference"),
            (BohrRadius, Length, 5.291_772_109_03e-11, "BohrRadius"),
            (ClassicalElectronRadius, Length, 2.817_940_326_2e-15, "ClassicalElectronRadius"),
            (PlanckLength, Length, 1.616_255e-35, "PlanckLength"),
            (ElectronReducedComptonWavelength, Length, 3.861_592_679_6e-13, "ElectronReducedComptonWavelength"),
            (NominalSolarRadius, Length, 695_700_000.0, "NominalSolarRadius"),
            (NominalEarthRadius, Length, 6_371_000.0, "NominalEarthRadius"),
            (NominalEarthEquatorialRadius, Length, 6_378_137.0, "NominalEarthEquatorialRadius"),
            (NominalEarthPolarRadius, Length, 6_356_752.3142, "NominalEarthPolarRadius"),
            (NominalLunarRadius, Length, 1_737_400.0, "NominalLunarRadius"),
            (NominalJupiterRadius, Length, 71_492_000.0, "NominalJupiterRadius"),
            (NominalLunarDistance, Length, 384_400_000.0, "NominalLunarDistance"),
            (NominalSolarDiameter, Length, 1_391_400_000.0, "NominalSolarDiameter"),
            
            // Time units (canonical: Second = 1.0)
            (Second, Time, 1.0, "Second"),
            (Attosecond, Time, 1e-18, "Attosecond"),
            (Femtosecond, Time, 1e-15, "Femtosecond"),
            (Picosecond, Time, 1e-12, "Picosecond"),
            (Nanosecond, Time, 1e-9, "Nanosecond"),
            (Microsecond, Time, 1e-6, "Microsecond"),
            (Millisecond, Time, 1e-3, "Millisecond"),
            (Centisecond, Time, 1e-2, "Centisecond"),
            (Decisecond, Time, 1e-1, "Decisecond"),
            (Decasecond, Time, 10.0, "Decasecond"),
            (Hectosecond, Time, 100.0, "Hectosecond"),
            (Kilosecond, Time, 1_000.0, "Kilosecond"),
            (Megasecond, Time, 1e6, "Megasecond"),
            (Gigasecond, Time, 1e9, "Gigasecond"),
            (Terasecond, Time, 1e12, "Terasecond"),
            (Minute, Time, 60.0, "Minute"),
            (Hour, Time, 3_600.0, "Hour"),
            (Day, Time, SECONDS_PER_DAY, "Day"),
            (Week, Time, SECONDS_PER_DAY * 7.0, "Week"),
            (Fortnight, Time, SECONDS_PER_DAY * 14.0, "Fortnight"),
            (Year, Time, SECONDS_PER_YEAR, "Year"),
            (Decade, Time, SECONDS_PER_YEAR * 10.0, "Decade"),
            (Century, Time, SECONDS_PER_YEAR * 100.0, "Century"),
            (Millennium, Time, SECONDS_PER_YEAR * 1000.0, "Millennium"),
            (JulianYear, Time, SECONDS_PER_JULIAN_YEAR, "JulianYear"),
            (JulianCentury, Time, SECONDS_PER_DAY * 36_525.0, "JulianCentury"),
            (SiderealDay, Time, 86_164.0905, "SiderealDay"),
            (SynodicMonth, Time, 29.530_588 * SECONDS_PER_DAY, "SynodicMonth"),
            (SiderealYear, Time, 365.256_363_004 * SECONDS_PER_DAY, "SiderealYear"),
            
            // Angular units (canonical: Radian = 1.0 for FFI)
            (Radian, Angle, 1.0, "Radian"),
            (Degree, Angle, PI / 180.0, "Degree"),
            (Milliradian, Angle, 1e-3, "Milliradian"),
            (Arcminute, Angle, PI / 180.0 / 60.0, "Arcminute"),
            (Arcsecond, Angle, PI / 180.0 / 3_600.0, "Arcsecond"),
            (MilliArcsecond, Angle, PI / 180.0 / 3_600_000.0, "MilliArcsecond"),
            (MicroArcsecond, Angle, PI / 180.0 / 3_600_000_000.0, "MicroArcsecond"),
            (Gradian, Angle, PI / 200.0, "Gradian"),
            (Turn, Angle, 2.0 * PI, "Turn"),
            (HourAngle, Angle, PI / 12.0, "HourAngle"),
            
            // Mass units (canonical: Gram = 1.0)
            (Gram, Mass, 1.0, "Gram"),
            (Yoctogram, Mass, 1e-24, "Yoctogram"),
            (Zeptogram, Mass, 1e-21, "Zeptogram"),
            (Attogram, Mass, 1e-18, "Attogram"),
            (Femtogram, Mass, 1e-15, "Femtogram"),
            (Picogram, Mass, 1e-12, "Picogram"),
            (Nanogram, Mass, 1e-9, "Nanogram"),
            (Microgram, Mass, 1e-6, "Microgram"),
            (Milligram, Mass, 1e-3, "Milligram"),
            (Centigram, Mass, 1e-2, "Centigram"),
            (Decigram, Mass, 1e-1, "Decigram"),
            (Decagram, Mass, 1e1, "Decagram"),
            (Hectogram, Mass, 1e2, "Hectogram"),
            (Kilogram, Mass, 1e3, "Kilogram"),
            (Megagram, Mass, 1e6, "Megagram"),
            (Gigagram, Mass, 1e9, "Gigagram"),
            (Teragram, Mass, 1e12, "Teragram"),
            (Petagram, Mass, 1e15, "Petagram"),
            (Exagram, Mass, 1e18, "Exagram"),
            (Zettagram, Mass, 1e21, "Zettagram"),
            (Yottagram, Mass, 1e24, "Yottagram"),
            (Tonne, Mass, 1_000_000.0, "Tonne"),
            (Carat, Mass, 0.2, "Carat"),
            (Grain, Mass, 0.064_798_91, "Grain"),
            (Pound, Mass, 453.59237, "Pound"),
            (Ounce, Mass, 28.349523125, "Ounce"),
            (Stone, Mass, 6_350.29318, "Stone"),
            (ShortTon, Mass, 907_184.74, "ShortTon"),
            (LongTon, Mass, 1_016_046.9088, "LongTon"),
            (AtomicMassUnit, Mass, 1.660_539_068_92e-24, "AtomicMassUnit"),
            (SolarMass, Mass, 1.988_416e33, "SolarMass"),
            
            // Power units (canonical: Watt = 1.0)
            (Watt, Power, 1.0, "Watt"),
            (Yoctowatt, Power, 1e-24, "Yoctowatt"),
            (Zeptowatt, Power, 1e-21, "Zeptowatt"),
            (Attowatt, Power, 1e-18, "Attowatt"),
            (Femtowatt, Power, 1e-15, "Femtowatt"),
            (Picowatt, Power, 1e-12, "Picowatt"),
            (Nanowatt, Power, 1e-9, "Nanowatt"),
            (Microwatt, Power, 1e-6, "Microwatt"),
            (Milliwatt, Power, 1e-3, "Milliwatt"),
            (Deciwatt, Power, 1e-1, "Deciwatt"),
            (Decawatt, Power, 1e1, "Decawatt"),
            (Hectowatt, Power, 1e2, "Hectowatt"),
            (Kilowatt, Power, 1e3, "Kilowatt"),
            (Megawatt, Power, 1e6, "Megawatt"),
            (Gigawatt, Power, 1e9, "Gigawatt"),
            (Terawatt, Power, 1e12, "Terawatt"),
            (Petawatt, Power, 1e15, "Petawatt"),
            (Exawatt, Power, 1e18, "Exawatt"),
            (Zettawatt, Power, 1e21, "Zettawatt"),
            (Yottawatt, Power, 1e24, "Yottawatt"),
            (ErgPerSecond, Power, 1e-7, "ErgPerSecond"),
            (HorsepowerMetric, Power, 735.49875, "HorsepowerMetric"),
            (HorsepowerElectric, Power, 746.0, "HorsepowerElectric"),
            (SolarLuminosity, Power, 3.828e26, "SolarLuminosity"),
        ]
    };
}

pub(crate) use define_registry_entries;
