//! Auto-generated unit data for FFI.
//!
//! This module contains macros that define all units with their metadata.
//! This serves as the single source of truth for unit definitions in the FFI layer.

use core::f64::consts::PI;

// Precomputed constants for complex expressions
const METERS_PER_LIGHT_YEAR: f64 = 9_460_730_472_580_800.0; // 299_792_458.0 * 86_400.0 * 365.25
const METERS_PER_PARSEC: f64 = 30_856_775_814_913_672.8; // AU * 648_000 / PI
const SECONDS_PER_DAY: f64 = 86_400.0;
const SECONDS_PER_YEAR: f64 = 31_556_952.0; // 365.2425 * 86400
const SECONDS_PER_JULIAN_YEAR: f64 = 31_557_600.0; // 365.25 * 86400

/// Macro to generate unit name strings (for name() method)
macro_rules! define_unit_names {
    () => {
        $crate::unit_match_arms![
            // Length
            (Meter, "Meter"),
            (Yoctometer, "Yoctometer"),
            (Zeptometer, "Zeptometer"),
            (Attometer, "Attometer"),
            (Femtometer, "Femtometer"),
            (Picometer, "Picometer"),
            (Nanometer, "Nanometer"),
            (Micrometer, "Micrometer"),
            (Millimeter, "Millimeter"),
            (Centimeter, "Centimeter"),
            (Decimeter, "Decimeter"),
            (Decameter, "Decameter"),
            (Hectometer, "Hectometer"),
            (Kilometer, "Kilometer"),
            (Megameter, "Megameter"),
            (Gigameter, "Gigameter"),
            (Terameter, "Terameter"),
            (Petameter, "Petameter"),
            (Exameter, "Exameter"),
            (Zettameter, "Zettameter"),
            (Yottameter, "Yottameter"),
            (AstronomicalUnit, "AstronomicalUnit"),
            (LightYear, "LightYear"),
            (Parsec, "Parsec"),
            (Kiloparsec, "Kiloparsec"),
            (Megaparsec, "Megaparsec"),
            (Gigaparsec, "Gigaparsec"),
            (Inch, "Inch"),
            (Foot, "Foot"),
            (Yard, "Yard"),
            (Mile, "Mile"),
            (NauticalMile, "NauticalMile"),
            (Chain, "Chain"),
            (Rod, "Rod"),
            (Link, "Link"),
            (Fathom, "Fathom"),
            (EarthMeridionalCircumference, "EarthMeridionalCircumference"),
            (EarthEquatorialCircumference, "EarthEquatorialCircumference"),
            (BohrRadius, "BohrRadius"),
            (ClassicalElectronRadius, "ClassicalElectronRadius"),
            (PlanckLength, "PlanckLength"),
            (ElectronReducedComptonWavelength, "ElectronReducedComptonWavelength"),
            (NominalSolarRadius, "NominalSolarRadius"),
            (NominalEarthRadius, "NominalEarthRadius"),
            (NominalEarthEquatorialRadius, "NominalEarthEquatorialRadius"),
            (NominalEarthPolarRadius, "NominalEarthPolarRadius"),
            (NominalLunarRadius, "NominalLunarRadius"),
            (NominalJupiterRadius, "NominalJupiterRadius"),
            (NominalLunarDistance, "NominalLunarDistance"),
            (NominalSolarDiameter, "NominalSolarDiameter"),
            // Time
            (Second, "Second"),
            (Attosecond, "Attosecond"),
            (Femtosecond, "Femtosecond"),
            (Picosecond, "Picosecond"),
            (Nanosecond, "Nanosecond"),
            (Microsecond, "Microsecond"),
            (Millisecond, "Millisecond"),
            (Centisecond, "Centisecond"),
            (Decisecond, "Decisecond"),
            (Decasecond, "Decasecond"),
            (Hectosecond, "Hectosecond"),
            (Kilosecond, "Kilosecond"),
            (Megasecond, "Megasecond"),
            (Gigasecond, "Gigasecond"),
            (Terasecond, "Terasecond"),
            (Minute, "Minute"),
            (Hour, "Hour"),
            (Day, "Day"),
            (Week, "Week"),
            (Fortnight, "Fortnight"),
            (Year, "Year"),
            (Decade, "Decade"),
            (Century, "Century"),
            (Millennium, "Millennium"),
            (JulianYear, "JulianYear"),
            (JulianCentury, "JulianCentury"),
            (SiderealDay, "SiderealDay"),
            (SynodicMonth, "SynodicMonth"),
            (SiderealYear, "SiderealYear"),
            // Angular
            (Radian, "Radian"),
            (Degree, "Degree"),
            (Milliradian, "Milliradian"),
            (Arcminute, "Arcminute"),
            (Arcsecond, "Arcsecond"),
            (MilliArcsecond, "MilliArcsecond"),
            (MicroArcsecond, "MicroArcsecond"),
            (Gradian, "Gradian"),
            (Turn, "Turn"),
            (HourAngle, "HourAngle"),
            // Mass
            (Gram, "Gram"),
            (Yoctogram, "Yoctogram"),
            (Zeptogram, "Zeptogram"),
            (Attogram, "Attogram"),
            (Femtogram, "Femtogram"),
            (Picogram, "Picogram"),
            (Nanogram, "Nanogram"),
            (Microgram, "Microgram"),
            (Milligram, "Milligram"),
            (Centigram, "Centigram"),
            (Decigram, "Decigram"),
            (Decagram, "Decagram"),
            (Hectogram, "Hectogram"),
            (Kilogram, "Kilogram"),
            (Megagram, "Megagram"),
            (Gigagram, "Gigagram"),
            (Teragram, "Teragram"),
            (Petagram, "Petagram"),
            (Exagram, "Exagram"),
            (Zettagram, "Zettagram"),
            (Yottagram, "Yottagram"),
            (Tonne, "Tonne"),
            (Carat, "Carat"),
            (Grain, "Grain"),
            (Pound, "Pound"),
            (Ounce, "Ounce"),
            (Stone, "Stone"),
            (ShortTon, "ShortTon"),
            (LongTon, "LongTon"),
            (AtomicMassUnit, "AtomicMassUnit"),
            (SolarMass, "SolarMass"),
            // Power
            (Watt, "Watt"),
            (Yoctowatt, "Yoctowatt"),
            (Zeptowatt, "Zeptowatt"),
            (Attowatt, "Attowatt"),
            (Femtowatt, "Femtowatt"),
            (Picowatt, "Picowatt"),
            (Nanowatt, "Nanowatt"),
            (Microwatt, "Microwatt"),
            (Milliwatt, "Milliwatt"),
            (Deciwatt, "Deciwatt"),
            (Decawatt, "Decawatt"),
            (Hectowatt, "Hectowatt"),
            (Kilowatt, "Kilowatt"),
            (Megawatt, "Megawatt"),
            (Gigawatt, "Gigawatt"),
            (Terawatt, "Terawatt"),
            (Petawatt, "Petawatt"),
            (Exawatt, "Exawatt"),
            (Zettawatt, "Zettawatt"),
            (Yottawatt, "Yottawatt"),
            (ErgPerSecond, "ErgPerSecond"),
            (HorsepowerMetric, "HorsepowerMetric"),
            (HorsepowerElectric, "HorsepowerElectric"),
            (SolarLuminosity, "SolarLuminosity"),
        ]
    };
}

///  to generate unit name C strings (for name_cstr() method)
#[macro_export]
macro_rules! define_unit_names_cstr {
    () => {
        // This expands to match arms directly - no wrapping
        UnitId::Meter => b"Meter\0".as_ptr() as *const c_char,
        UnitId::Yoctometer => b"Yoctometer\0".as_ptr() as *const c_char,
        UnitId::Zeptometer => b"Zeptometer\0".as_ptr() as *const c_char,
        UnitId::Attometer => b"Attometer\0".as_ptr() as *const c_char,
        UnitId::Femtometer => b"Femtometer\0".as_ptr() as *const c_char,
        UnitId::Picometer => b"Picometer\0".as_ptr() as *const c_char,
        UnitId::Nanometer => b"Nanometer\0".as_ptr() as *const c_char,
        UnitId::Micrometer => b"Micrometer\0".as_ptr() as *const c_char,
        UnitId::Millimeter => b"Millimeter\0".as_ptr() as *const c_char,
        UnitId::Centimeter => b"Centimeter\0".as_ptr() as *const c_char,
        UnitId::Decimeter => b"Decimeter\0".as_ptr() as *const c_char,
        UnitId::Decameter => b"Decameter\0".as_ptr() as *const c_char,
        UnitId::Hectometer => b"Hectometer\0".as_ptr() as *const c_char,
        UnitId::Kilometer => b"Kilometer\0".as_ptr() as *const c_char,
        UnitId::Megameter => b"Megameter\0".as_ptr() as *const c_char,
        UnitId::Gigameter => b"Gigameter\0".as_ptr() as *const c_char,
        UnitId::Terameter => b"Terameter\0".as_ptr() as *const c_char,
        UnitId::Petameter => b"Petameter\0".as_ptr() as *const c_char,
        UnitId::Exameter => b"Exameter\0".as_ptr() as *const c_char,
        UnitId::Zettameter => b"Zettameter\0".as_ptr() as *const c_char,
        UnitId::Yottameter => b"Yottameter\0".as_ptr() as *const c_char,
        UnitId::AstronomicalUnit => b"AstronomicalUnit\0".as_ptr() as *const c_char,
        UnitId::LightYear => b"LightYear\0".as_ptr() as *const c_char,
        UnitId::Parsec => b"Parsec\0".as_ptr() as *const c_char,
        UnitId::Kiloparsec => b"Kiloparsec\0".as_ptr() as *const c_char,
        UnitId::Megaparsec => b"Megaparsec\0".as_ptr() as *const c_char,
        UnitId::Gigaparsec => b"Gigaparsec\0".as_ptr() as *const c_char,
        UnitId::Inch => b"Inch\0".as_ptr() as *const c_char,
        UnitId::Foot => b"Foot\0".as_ptr() as *const c_char,
        UnitId::Yard => b"Yard\0".as_ptr() as *const c_char,
        UnitId::Mile => b"Mile\0".as_ptr() as *const c_char,
        UnitId::NauticalMile => b"NauticalMile\0".as_ptr() as *const c_char,
        UnitId::Chain => b"Chain\0".as_ptr() as *const c_char,
        UnitId::Rod => b"Rod\0".as_ptr() as *const c_char,
        UnitId::Link => b"Link\0".as_ptr() as *const c_char,
        UnitId::Fathom => b"Fathom\0".as_ptr() as *const c_char,
        UnitId::EarthMeridionalCircumference => b"EarthMeridionalCircumference\0".as_ptr() as *const c_char,
        UnitId::EarthEquatorialCircumference => b"EarthEquatorialCircumference\0".as_ptr() as *const c_char,
        UnitId::BohrRadius => b"BohrRadius\0".as_ptr() as *const c_char,
        UnitId::ClassicalElectronRadius => b"ClassicalElectronRadius\0".as_ptr() as *const c_char,
        UnitId::PlanckLength => b"PlanckLength\0".as_ptr() as *const c_char,
        UnitId::ElectronReducedComptonWavelength => b"ElectronReducedComptonWavelength\0".as_ptr() as *const c_char,
        UnitId::NominalSolarRadius => b"NominalSolarRadius\0".as_ptr() as *const c_char,
        UnitId::NominalEarthRadius => b"NominalEarthRadius\0".as_ptr() as *const c_char,
        UnitId::NominalEarthEquatorialRadius => b"NominalEarthEquatorialRadius\0".as_ptr() as *const c_char,
        UnitId::NominalEarthPolarRadius => b"NominalEarthPolarRadius\0".as_ptr() as *const c_char,
        UnitId::NominalLunarRadius => b"NominalLunarRadius\0".as_ptr() as *const c_char,
        UnitId::NominalJupiterRadius => b"NominalJupiterRadius\0".as_ptr() as *const c_char,
        UnitId::NominalLunarDistance => b"NominalLunarDistance\0".as_ptr() as *const c_char,
        UnitId::NominalSolarDiameter => b"NominalSolarDiameter\0".as_ptr() as *const c_char,
        // Time
        UnitId::Second => b"Second\0".as_ptr() as *const c_char,
        UnitId::Attosecond => b"Attosecond\0".as_ptr() as *const c_char,
        UnitId::Femtosecond => b"Femtosecond\0".as_ptr() as *const c_char,
        UnitId::Picosecond => b"Picosecond\0".as_ptr() as *const c_char,
        UnitId::Nanosecond => b"Nanosecond\0".as_ptr() as *const c_char,
        UnitId::Microsecond => b"Microsecond\0".as_ptr() as *const c_char,
        UnitId::Millisecond => b"Millisecond\0".as_ptr() as *const c_char,
        UnitId::Centisecond => b"Centisecond\0".as_ptr() as *const c_char,
        UnitId::Decisecond => b"Decisecond\0".as_ptr() as *const c_char,
        UnitId::Decasecond => b"Decasecond\0".as_ptr() as *const c_char,
        UnitId::Hectosecond => b"Hectosecond\0".as_ptr() as *const c_char,
        UnitId::Kilosecond => b"Kilosecond\0".as_ptr() as *const c_char,
        UnitId::Megasecond => b"Megasecond\0".as_ptr() as *const c_char,
        UnitId::Gigasecond => b"Gigasecond\0".as_ptr() as *const c_char,
        UnitId::Terasecond => b"Terasecond\0".as_ptr() as *const c_char,
        UnitId::Minute => b"Minute\0".as_ptr() as *const c_char,
        UnitId::Hour => b"Hour\0".as_ptr() as *const c_char,
        UnitId::Day => b"Day\0".as_ptr() as *const c_char,
        UnitId::Week => b"Week\0".as_ptr() as *const c_char,
        UnitId::Fortnight => b"Fortnight\0".as_ptr() as *const c_char,
        UnitId::Year => b"Year\0".as_ptr() as *const c_char,
        UnitId::Decade => b"Decade\0".as_ptr() as *const c_char,
        UnitId::Century => b"Century\0".as_ptr() as *const c_char,
        UnitId::Millennium => b"Millennium\0".as_ptr() as *const c_char,
        UnitId::JulianYear => b"JulianYear\0".as_ptr() as *const c_char,
        UnitId::JulianCentury => b"JulianCentury\0".as_ptr() as *const c_char,
        UnitId::SiderealDay => b"SiderealDay\0".as_ptr() as *const c_char,
        UnitId::SynodicMonth => b"SynodicMonth\0".as_ptr() as *const c_char,
        UnitId::SiderealYear => b"SiderealYear\0".as_ptr() as *const c_char,
        // Angular
        UnitId::Radian => b"Radian\0".as_ptr() as *const c_char,
        UnitId::Degree => b"Degree\0".as_ptr() as *const c_char,
        UnitId::Milliradian => b"Milliradian\0".as_ptr() as *const c_char,
        UnitId::Arcminute => b"Arcminute\0".as_ptr() as *const c_char,
        UnitId::Arcsecond => b"Arcsecond\0".as_ptr() as *const c_char,
        UnitId::MilliArcsecond => b"MilliArcsecond\0".as_ptr() as *const c_char,
        UnitId::MicroArcsecond => b"MicroArcsecond\0".as_ptr() as *const c_char,
        UnitId::Gradian => b"Gradian\0".as_ptr() as *const c_char,
        UnitId::Turn => b"Turn\0".as_ptr() as *const c_char,
        UnitId::HourAngle => b"HourAngle\0".as_ptr() as *const c_char,
        // Mass
        UnitId::Gram => b"Gram\0".as_ptr() as *const c_char,
        UnitId::Yoctogram => b"Yoctogram\0".as_ptr() as *const c_char,
        UnitId::Zeptogram => b"Zeptogram\0".as_ptr() as *const c_char,
        UnitId::Attogram => b"Attogram\0".as_ptr() as *const c_char,
        UnitId::Femtogram => b"Femtogram\0".as_ptr() as *const c_char,
        UnitId::Picogram => b"Picogram\0".as_ptr() as *const c_char,
        UnitId::Nanogram => b"Nanogram\0".as_ptr() as *const c_char,
        UnitId::Microgram => b"Microgram\0".as_ptr() as *const c_char,
        UnitId::Milligram => b"Milligram\0".as_ptr() as *const c_char,
        UnitId::Centigram => b"Centigram\0".as_ptr() as *const c_char,
        UnitId::Decigram => b"Decigram\0".as_ptr() as *const c_char,
        UnitId::Decagram => b"Decagram\0".as_ptr() as *const c_char,
        UnitId::Hectogram => b"Hectogram\0".as_ptr() as *const c_char,
        UnitId::Kilogram => b"Kilogram\0".as_ptr() as *const c_char,
        UnitId::Megagram => b"Megagram\0".as_ptr() as *const c_char,
        UnitId::Gigagram => b"Gigagram\0".as_ptr() as *const c_char,
        UnitId::Teragram => b"Teragram\0".as_ptr() as *const c_char,
        UnitId::Petagram => b"Petagram\0".as_ptr() as *const c_char,
        UnitId::Exagram => b"Exagram\0".as_ptr() as *const c_char,
        UnitId::Zettagram => b"Zettagram\0".as_ptr() as *const c_char,
        UnitId::Yottagram => b"Yottagram\0".as_ptr() as *const c_char,
        UnitId::Tonne => b"Tonne\0".as_ptr() as *const c_char,
        UnitId::Carat => b"Carat\0".as_ptr() as *const c_char,
        UnitId::Grain => b"Grain\0".as_ptr() as *const c_char,
        UnitId::Pound => b"Pound\0".as_ptr() as *const c_char,
        UnitId::Ounce => b"Ounce\0".as_ptr() as *const c_char,
        UnitId::Stone => b"Stone\0".as_ptr() as *const c_char,
        UnitId::ShortTon => b"ShortTon\0".as_ptr() as *const c_char,
        UnitId::LongTon => b"LongTon\0".as_ptr() as *const c_char,
        UnitId::AtomicMassUnit => b"AtomicMassUnit\0".as_ptr() as *const c_char,
        UnitId::SolarMass => b"SolarMass\0".as_ptr() as *const c_char,
        // Power
        UnitId::Watt => b"Watt\0".as_ptr() as *const c_char,
        UnitId::Yoctowatt => b"Yoctowatt\0".as_ptr() as *const c_char,
        UnitId::Zeptowatt => b"Zeptowatt\0".as_ptr() as *const c_char,
        UnitId::Attowatt => b"Attowatt\0".as_ptr() as *const c_char,
        UnitId::Femtowatt => b"Femtowatt\0".as_ptr() as *const c_char,
        UnitId::Picowatt => b"Picowatt\0".as_ptr() as *const c_char,
        UnitId::Nanowatt => b"Nanowatt\0".as_ptr() as *const c_char,
        UnitId::Microwatt => b"Microwatt\0".as_ptr() as *const c_char,
        UnitId::Milliwatt => b"Milliwatt\0".as_ptr() as *const c_char,
        UnitId::Deciwatt => b"Deciwatt\0".as_ptr() as *const c_char,
        UnitId::Decawatt => b"Decawatt\0".as_ptr() as *const c_char,
        UnitId::Hectowatt => b"Hectowatt\0".as_ptr() as *const c_char,
        UnitId::Kilowatt => b"Kilowatt\0".as_ptr() as *const c_char,
        UnitId::Megawatt => b"Megawatt\0".as_ptr() as *const c_char,
        UnitId::Gigawatt => b"Gigawatt\0".as_ptr() as *const c_char,
        UnitId::Terawatt => b"Terawatt\0".as_ptr() as *const c_char,
        UnitId::Petawatt => b"Petawatt\0".as_ptr() as *const c_char,
        UnitId::Exawatt => b"Exawatt\0".as_ptr() as *const c_char,
        UnitId::Zettawatt => b"Zettawatt\0".as_ptr() as *const c_char,
        UnitId::Yottawatt => b"Yottawatt\0".as_ptr() as *const c_char,
        UnitId::ErgPerSecond => b"ErgPerSecond\0".as_ptr() as *const c_char,
        UnitId::HorsepowerMetric => b"HorsepowerMetric\0".as_ptr() as *const c_char,
        UnitId::HorsepowerElectric => b"HorsepowerElectric\0".as_ptr() as *const c_char,
        UnitId::SolarLuminosity => b"SolarLuminosity\0".as_ptr() as *const c_char,
    };
}

/// Macro to generate unit name strings (for name() method)
macro_rules! define_unit_names {
    () => {
        $crate::unit_match_arms![
            // Length
            (Meter, "Meter"),
            (Yoctometer, "Yoctometer"),
            (Zeptometer, "Zeptometer"),
            (Attometer, "Attometer"),
            (Femtometer, "Femtometer"),
            (Picometer, "Picometer"),
            (Nanometer, "Nanometer"),
            (Micrometer, "Micrometer"),
            (Millimeter, "Millimeter"),
            (Centimeter, "Centimeter"),
            (Decimeter, "Decimeter"),
            (Decameter, "Decameter"),
            (Hectometer, "Hectometer"),
            (Kilometer, "Kilometer"),
            (Megameter, "Megameter"),
            (Gigameter, "Gigameter"),
            (Terameter, "Terameter"),
            (Petameter, "Petameter"),
            (Exameter, "Exameter"),
            (Zettameter, "Zettameter"),
            (Yottameter, "Yottameter"),
            (AstronomicalUnit, "AstronomicalUnit"),
            (LightYear, "LightYear"),
            (Parsec, "Parsec"),
            (Kiloparsec, "Kiloparsec"),
            (Megaparsec, "Megaparsec"),
            (Gigaparsec, "Gigaparsec"),
            (Inch, "Inch"),
            (Foot, "Foot"),
            (Yard, "Yard"),
            (Mile, "Mile"),
            (NauticalMile, "NauticalMile"),
            (Chain, "Chain"),
            (Rod, "Rod"),
            (Link, "Link"),
            (Fathom, "Fathom"),
            (EarthMeridionalCircumference, "EarthMeridionalCircumference"),
            (EarthEquatorialCircumference, "EarthEquatorialCircumference"),
            (BohrRadius, "BohrRadius"),
            (ClassicalElectronRadius, "ClassicalElectronRadius"),
            (PlanckLength, "PlanckLength"),
            (ElectronReducedComptonWavelength, "ElectronReducedComptonWavelength"),
            (NominalSolarRadius, "NominalSolarRadius"),
            (NominalEarthRadius, "NominalEarthRadius"),
            (NominalEarthEquatorialRadius, "NominalEarthEquatorialRadius"),
            (NominalEarthPolarRadius, "NominalEarthPolarRadius"),
            (NominalLunarRadius, "NominalLunarRadius"),
            (NominalJupiterRadius, "NominalJupiterRadius"),
            (NominalLunarDistance, "NominalLunarDistance"),
            (NominalSolarDiameter, "NominalSolarDiameter"),
            // Time
            (Second, "Second"),
            (Attosecond, "Attosecond"),
            (Femtosecond, "Femtosecond"),
            (Picosecond, "Picosecond"),
            (Nanosecond, "Nanosecond"),
            (Microsecond, "Microsecond"),
            (Millisecond, "Millisecond"),
            (Centisecond, "Centisecond"),
            (Decisecond, "Decisecond"),
            (Decasecond, "Decasecond"),
            (Hectosecond, "Hectosecond"),
            (Kilosecond, "Kilosecond"),
            (Megasecond, "Megasecond"),
            (Gigasecond, "Gigasecond"),
            (Terasecond, "Terasecond"),
            (Minute, "Minute"),
            (Hour, "Hour"),
            (Day, "Day"),
            (Week, "Week"),
            (Fortnight, "Fortnight"),
            (Year, "Year"),
            (Decade, "Decade"),
            (Century, "Century"),
            (Millennium, "Millennium"),
            (JulianYear, "JulianYear"),
            (JulianCentury, "JulianCentury"),
            (SiderealDay, "SiderealDay"),
            (SynodicMonth, "SynodicMonth"),
            (SiderealYear, "SiderealYear"),
            // Angular
            (Radian, "Radian"),
            (Degree, "Degree"),
            (Milliradian, "Milliradian"),
            (Arcminute, "Arcminute"),
            (Arcsecond, "Arcsecond"),
            (MilliArcsecond, "MilliArcsecond"),
            (MicroArcsecond, "MicroArcsecond"),
            (Gradian, "Gradian"),
            (Turn, "Turn"),
            (HourAngle, "HourAngle"),
            // Mass
            (Gram, "Gram"),
            (Yoctogram, "Yoctogram"),
            (Zeptogram, "Zeptogram"),
            (Attogram, "Attogram"),
            (Femtogram, "Femtogram"),
            (Picogram, "Picogram"),
            (Nanogram, "Nanogram"),
            (Microgram, "Microgram"),
            (Milligram, "Milligram"),
            (Centigram, "Centigram"),
            (Decigram, "Decigram"),
            (Decagram, "Decagram"),
            (Hectogram, "Hectogram"),
            (Kilogram, "Kilogram"),
            (Megagram, "Megagram"),
            (Gigagram, "Gigagram"),
            (Teragram, "Teragram"),
            (Petagram, "Petagram"),
            (Exagram, "Exagram"),
            (Zettagram, "Zettagram"),
            (Yottagram, "Yottagram"),
            (Tonne, "Tonne"),
            (Carat, "Carat"),
            (Grain, "Grain"),
            (Pound, "Pound"),
            (Ounce, "Ounce"),
            (Stone, "Stone"),
            (ShortTon, "ShortTon"),
            (LongTon, "LongTon"),
            (AtomicMassUnit, "AtomicMassUnit"),
            (SolarMass, "SolarMass"),
            // Power
            (Watt, "Watt"),
            (Yoctowatt, "Yoctowatt"),
            (Zeptowatt, "Zeptowatt"),
            (Attowatt, "Attowatt"),
            (Femtowatt, "Femtowatt"),
            (Picowatt, "Picowatt"),
            (Nanowatt, "Nanowatt"),
            (Microwatt, "Microwatt"),
            (Milliwatt, "Milliwatt"),
            (Deciwatt, "Deciwatt"),
            (Decawatt, "Decawatt"),
            (Hectowatt, "Hectowatt"),
            (Kilowatt, "Kilowatt"),
            (Megawatt, "Megawatt"),
            (Gigawatt, "Gigawatt"),
            (Terawatt, "Terawatt"),
            (Petawatt, "Petawatt"),
            (Exawatt, "Exawatt"),
            (Zettawatt, "Zettawatt"),
            (Yottawatt, "Yottawatt"),
            (ErgPerSecond, "ErgPerSecond"),
            (HorsepowerMetric, "HorsepowerMetric"),
            (HorsepowerElectric, "HorsepowerElectric"),
            (SolarLuminosity, "SolarLuminosity"),
        ]
    };
}

/// Macro to generate from_u32 match arms
macro_rules! define_unit_from_u32 {
    () => {
        $crate::unit_from_u32_arms![
            // Length (100-199)
            (100, Meter), (101, Yoctometer), (102, Zeptometer), (103, Attometer),
            (104, Femtometer), (105, Picometer), (106, Nanometer), (107, Micrometer),
            (108, Millimeter), (109, Centimeter), (110, Decimeter), (111, Decameter),
            (112, Hectometer), (113, Kilometer), (114, Megameter), (115, Gigameter),
            (116, Terameter), (117, Petameter), (118, Exameter), (119, Zettameter),
            (120, Yottameter), (121, AstronomicalUnit), (122, LightYear), (123, Parsec),
            (124, Kiloparsec), (125, Megaparsec), (126, Gigaparsec), (127, Inch),
            (128, Foot), (129, Yard), (130, Mile), (131, NauticalMile), (132, Chain),
            (133, Rod), (134, Link), (135, Fathom), (136, EarthMeridionalCircumference),
            (137, EarthEquatorialCircumference), (138, BohrRadius), (139, ClassicalElectronRadius),
            (140, PlanckLength), (141, ElectronReducedComptonWavelength),
            (150, NominalSolarRadius), (151, NominalEarthRadius), (152, NominalEarthEquatorialRadius),
            (153, NominalEarthPolarRadius), (154, NominalLunarRadius), (155, NominalJupiterRadius),
            (156, NominalLunarDistance), (157, NominalSolarDiameter),
            // Time (200-299)
            (200, Second), (201, Attosecond), (202, Femtosecond), (203, Picosecond),
            (204, Nanosecond), (205, Microsecond), (206, Millisecond), (207, Centisecond),
            (208, Decisecond), (209, Decasecond), (210, Hectosecond), (211, Kilosecond),
            (212, Megasecond), (213, Gigasecond), (214, Terasecond), (215, Minute),
            (216, Hour), (217, Day), (218, Week), (219, Fortnight), (220, Year),
            (221, Decade), (222, Century), (223, Millennium), (224, JulianYear),
            (225, JulianCentury), (226, SiderealDay), (227, SynodicMonth), (228, SiderealYear),
            // Angular (300-399)
            (300, Radian), (301, Degree), (302, Milliradian), (303, Arcminute),
            (304, Arcsecond), (305, MilliArcsecond), (306, MicroArcsecond), (307, Gradian),
            (308, Turn), (309, HourAngle),
            // Mass (400-499)
            (400, Gram), (401, Yoctogram), (402, Zeptogram), (403, Attogram),
            (404, Femtogram), (405, Picogram), (406, Nanogram), (407, Microgram),
            (408, Milligram), (409, Centigram), (410, Decigram), (411, Decagram),
            (412, Hectogram), (413, Kilogram), (414, Megagram), (415, Gigagram),
            (416, Teragram), (417, Petagram), (418, Exagram), (419, Zettagram),
            (420, Yottagram), (421, Tonne), (422, Carat), (423, Grain),
            (424, Pound), (425, Ounce), (426, Stone), (427, ShortTon),
            (428, LongTon), (429, AtomicMassUnit), (430, SolarMass),
            // Power (500-599)
            (500, Watt), (501, Yoctowatt), (502, Zeptowatt), (503, Attowatt),
            (504, Femtowatt), (505, Picowatt), (506, Nanowatt), (507, Microwatt),
            (508, Milliwatt), (509, Deciwatt), (510, Decawatt), (511, Hectowatt),
            (512, Kilowatt), (513, Megawatt), (514, Gigawatt), (515, Terawatt),
            (516, Petawatt), (517, Exawatt), (518, Zettawatt), (519, Yottawatt),
            (520, ErgPerSecond), (521, HorsepowerMetric), (522, HorsepowerElectric),
            (523, SolarLuminosity),
        ]
    };
}

pub(crate) use define_unit_from_u32;
pub(crate) use define_unit_names;
pub(crate) use define_unit_names_cstr;
