# Configuration for Observation Scheduling Explainability Model
# Author: TSI Modeling Team
# Date: 2025-10-25

# Global settings
global:
  random_seed: 42
  project_name: "telescope_scheduling_explainability"
  version: "1.0.0"
  
# Data paths
paths:
  data_dir: "data/"
  output_dir: "src/tsi/modeling/artifacts"
  reports_dir: "src/tsi/modeling/reports"
  models_dir: "src/tsi/modeling/artifacts/models"
  preprocessor_dir: "src/tsi/modeling/artifacts/preprocessors"
  
# Data loading and processing
data:
  summary_file: "summary_final.csv"
  schedule_file: "../schedule_ap_iter_1.csv"  # Main schedule file
  
  # Variable definitions
  target_variable: "planificada"
  time_variable: "scheduled_period.start"  # For temporal split
  
  # Features to exclude from modeling
  exclude_features:
    - "Proposal"
    - "Science Target"
    - "Scheduled"
    - "Requested"
    - "Visibility"
  
# Temporal data splitting (prevents data leakage)
temporal_split:
  method: "continuous"  # "continuous" or "period"
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  time_column: "Proposal"  # Use Proposal ID as proxy for temporal order
  period_column: "iteration"  # For period-based split
  min_samples_per_split: 50  # Minimum samples required in each split
  
# Feature engineering
features:
  astronomical:
    # Derived astronomical features
    - "airmass"
    - "altitude_mean"
    - "altitude_max"
    - "azimuth_range"
    - "visibility_hours"
    - "num_visibility_windows"
    - "visibility_efficiency"
    - "night_fraction"
    
  operational:
    - "priority"
    - "duration_minutes"
    - "min_observation_minutes"
    - "period_saturation"
    - "competing_observations"
    
  coordinates:
    - "ra_deg"
    - "dec_deg"
    - "ra_sin"
    - "ra_cos"
    - "dec_sin"
    - "dec_cos"
    
  interactions:
    - "priority_x_saturation"
    - "priority_x_visibility"
    - "duration_x_visibility"
    
# Preprocessing
preprocessing:
  numeric:
    strategy: "standard"  # StandardScaler
    handle_missing: "median"
    
  categorical:
    strategy: "onehot"  # OneHotEncoder
    handle_unknown: "ignore"
    handle_missing: "constant"
    
  outliers:
    method: "clip"
    lower_quantile: 0.01
    upper_quantile: 0.99

# Model configurations
models:
  logistic_regression:
    enabled: true
    class_weight: "balanced"
    max_iter: 1000
    solver: "lbfgs"
    penalty: "l2"
    C: 1.0
    random_state: 42
    
  random_forest:
    enabled: true
    n_estimators: 200
    max_depth: 15
    min_samples_split: 10
    min_samples_leaf: 5
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1
    
  gradient_boosting:
    enabled: true
    n_estimators: 200
    learning_rate: 0.05
    max_depth: 7
    min_samples_split: 10
    min_samples_leaf: 5
    subsample: 0.8
    random_state: 42
    
# Class imbalance handling
class_imbalance:
  strategy: "class_weight"  # Options: "class_weight", "smote", "adasyn", "hybrid"
  smote_k_neighbors: 5
  smote_sampling_strategy: 0.5
  
# Model calibration
calibration:
  enabled: true
  method: "sigmoid"  # Options: "sigmoid", "isotonic"
  cv: 5
  
# Evaluation metrics
evaluation:
  metrics:
    - "roc_auc"
    - "pr_auc"
    - "brier_score"
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "log_loss"
    
  # Confusion matrix costs
  costs:
    false_positive: 1.0  # Cost of predicting scheduled when not scheduled
    false_negative: 5.0  # Cost of predicting not scheduled when scheduled
    
  # Threshold optimization
  threshold:
    method: "cost_minimization"  # Options: "cost_minimization", "f1_optimal", "youden_index"
    search_space: [0.1, 0.9]
    search_steps: 100
    
  # Cross-validation for stability
  cv_folds: 5
  stratified: true
  
# Explainability configuration
explainability:
  global:
    # Feature importance
    permutation_importance:
      enabled: true
      n_repeats: 10
      random_state: 42
      
    # Partial Dependence Plots
    pdp:
      enabled: true
      features: ["priority", "visibility_hours", "period_saturation", "altitude_mean"]
      n_jobs: -1
      
    # SHAP global analysis
    shap_summary:
      enabled: true
      max_samples: 1000  # For computational efficiency
      
    # Feature interactions
    interactions:
      enabled: true
      top_n: 5
      
  local:
    # SHAP values per observation
    shap_local:
      enabled: true
      
    # LIME explanations
    lime:
      enabled: false  # Optional, SHAP is preferred
      num_features: 10
      num_samples: 5000
      
    # Explanation text generation
    explanation_template: |
      Observation {id}: {decision}
      Scheduling probability: {probability:.2%}

      Top factors:
      {top_factors}

      Recommendation: {recommendation}
      
# Robustness analysis
robustness:
  # Segmentation analysis
  segments:
    - name: "sky_region"
      bins: 4  # Quadrants
      
    - name: "priority_level"
      bins: ["Low", "Medium", "High", "Critical"]
      
    - name: "visibility_class"
      bins: 3  # Low, Medium, High
      
  # Perturbation tests
  perturbation:
    enabled: true
    feature_variations: [0.01, 0.05, 0.1]  # 1%, 5%, 10% change
    n_samples: 100
    
  # Temporal stability
  temporal_stability:
    enabled: true
    window_size: "1_iteration"  # Rolling window
    
# Reporting
reporting:
  formats: ["html", "json", "pdf"]
  
  include_sections:
    - "executive_summary"
    - "data_overview"
    - "model_performance"
    - "feature_importance"
    - "calibration_curves"
    - "confusion_matrix"
    - "shap_summary"
    - "example_explanations"
    - "robustness_analysis"
    - "recommendations"
    
  visualizations:
    dpi: 300
    style: "seaborn-v0_8-darkgrid"
    figure_size: [12, 8]
    color_palette: "viridis"
    
  # Number of example cases to include
  num_examples:
    scheduled: 5
    not_scheduled: 10
    
# Deployment and monitoring
deployment:
  api:
    enabled: false
    endpoint: "/predict"
    batch_size: 100
    
  monitoring:
    drift_detection:
      enabled: true
      reference_window: "train"
      method: "ks_test"  # Kolmogorov-Smirnov
      threshold: 0.05
      
    performance_tracking:
      enabled: true
      metrics: ["roc_auc", "pr_auc"]
      alert_threshold: 0.05  # 5% degradation
      
  retraining:
    trigger: "drift_detected"  # Options: "drift_detected", "performance_drop", "scheduled"
    schedule: "quarterly"
    min_new_data: 1000

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "src/tsi/modeling/artifacts/training.log"
  
# Reproducibility
reproducibility:
  lock_dependencies: true
  save_environment: true
  git_tracking: true
  data_versioning: true
