"""Report generation service for exporting analytics."""

import base64
import html
import logging

import pandas as pd
import plotly.graph_objects as go

from tsi.models.schemas import AnalyticsMetrics

logger = logging.getLogger(__name__)


def generate_markdown_report(
    metrics: AnalyticsMetrics,
    insights: list[str],
    correlations: pd.DataFrame,
    top_priority: pd.DataFrame,
    conflicts: pd.DataFrame,
) -> str:
    """
    Generate a comprehensive Markdown report.

    Args:
        metrics: Computed analytics metrics
        insights: List of insight strings
        correlations: Correlation matrix
        top_priority: Top observations by priority
        conflicts: Conflicting observations

    Returns:
        Markdown-formatted report as string
    """
    report = f"""# Telescope Scheduling Intelligence Report

## Executive Summary

- **Total Observations**: {metrics.total_observations:,}
- **Scheduled**: {metrics.scheduled_count:,} ({metrics.scheduling_rate * 100:.1f}%)
- **Unscheduled**: {metrics.unscheduled_count:,}
- **Mean Priority**: {metrics.mean_priority:.2f}
- **Total Visibility Hours**: {metrics.total_visibility_hours:,.0f}
- **Mean Requested Hours**: {metrics.mean_requested_hours:.2f}

## Key Insights

"""

    for insight in insights:
        report += f"- {insight}\n"

    report += "\n## Priority Statistics\n\n"
    report += f"- **Overall Mean Priority**: {metrics.mean_priority:.2f}\n"
    report += f"- **Median Priority**: {metrics.median_priority:.2f}\n"
    report += f"- **Scheduled Mean Priority**: {metrics.mean_priority_scheduled:.2f}\n"
    report += f"- **Unscheduled Mean Priority**: {metrics.mean_priority_unscheduled:.2f}\n"

    if not correlations.empty:
        report += "\n## Correlation Analysis (Spearman)\n\n"
        report += correlations.to_markdown()
        report += "\n"

    if not top_priority.empty:
        report += "\n## Top 10 Observations by Priority\n\n"
        report += top_priority.to_markdown(index=False)
        report += "\n"

    if not conflicts.empty:
        report += f"\n## ⚠️ Scheduling Conflicts ({len(conflicts)})\n\n"
        report += conflicts.to_markdown(index=False)
        report += "\n"

    report += "\n---\n\n"
    report += "*Generated by Telescope Scheduling Intelligence*\n"

    return report


def figure_to_base64(fig: go.Figure) -> str:
    """
    Convert Plotly figure to base64-encoded PNG.

    Args:
        fig: Plotly figure

    Returns:
        Base64-encoded PNG string, or empty string if conversion fails
    
    Raises:
        ValueError: If image export fails and strict error handling is needed
    """
    try:
        img_bytes = fig.to_image(format="png", width=800, height=600)
        return base64.b64encode(img_bytes).decode()
    except ImportError as e:
        # kaleido not installed
        logger.warning(f"Image export unavailable (install kaleido): {e}")
        return ""
    except Exception as e:
        # Other failures (rendering errors, etc.)
        logger.error(f"Failed to convert figure to image: {e}", exc_info=True)
        return ""


def _markdown_to_html_safe(markdown_text: str) -> str:
    """
    Convert Markdown to HTML safely, escaping user content properly.
    
    Uses a simple but safe approach that handles basic Markdown constructs
    without introducing XSS vulnerabilities from user-provided content.
    
    Args:
        markdown_text: Markdown-formatted text
    
    Returns:
        HTML-formatted text with proper escaping
    """
    # Try to use markdown library if available
    try:
        import markdown
        # Use safe mode with proper extensions
        return markdown.markdown(
            markdown_text,
            extensions=['tables', 'fenced_code', 'nl2br'],
            output_format='html5'
        )
    except ImportError:
        logger.warning("markdown library not available, using simple fallback conversion")
        # Fallback: simple line-by-line conversion with HTML escaping
        lines = markdown_text.split('\n')
        html_lines = []

        for line in lines:
            # Escape HTML entities first
            safe_line = html.escape(line)

            # Convert markdown headers
            if safe_line.startswith('# '):
                safe_line = f'<h1>{safe_line[2:]}</h1>'
            elif safe_line.startswith('## '):
                safe_line = f'<h2>{safe_line[3:]}</h2>'
            elif safe_line.startswith('### '):
                safe_line = f'<h3>{safe_line[4:]}</h3>'
            # Convert list items
            elif safe_line.startswith('- '):
                safe_line = f'<li>{safe_line[2:]}</li>'
            # Convert bold text (simple pattern)
            elif '**' in safe_line:
                # Already escaped, so replace the escaped pattern
                safe_line = safe_line.replace('**', '<strong>', 1).replace('**', '</strong>', 1)

            html_lines.append(safe_line)

        return '\n'.join(html_lines)


def generate_html_report(
    metrics: AnalyticsMetrics,
    insights: list[str],
    correlations: pd.DataFrame,
    top_priority: pd.DataFrame,
    conflicts: pd.DataFrame,
    figures: dict[str, go.Figure] | None = None,
) -> str:
    """
    Generate an HTML report with embedded charts.

    Args:
        metrics: Computed analytics metrics
        insights: List of insight strings
        correlations: Correlation matrix
        top_priority: Top observations by priority
        conflicts: Conflicting observations
        figures: Optional dict of figure name -> Plotly figure

    Returns:
        HTML-formatted report as string
    """
    # Start with markdown content
    md_content = generate_markdown_report(metrics, insights, correlations, top_priority, conflicts)

    # Convert markdown to HTML safely (escapes user content)
    html_content = _markdown_to_html_safe(md_content)

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Telescope Scheduling Intelligence Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            line-height: 1.6;
            color: #333;
        }}
        h1 {{
            color: #1f77b4;
            border-bottom: 2px solid #1f77b4;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #2c3e50;
            margin-top: 30px;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }}
        th {{
            background-color: #f0f2f6;
            font-weight: bold;
        }}
        tr:nth-child(even) {{
            background-color: #f9f9f9;
        }}
        li {{
            margin: 8px 0;
        }}
        .chart {{
            margin: 20px 0;
            text-align: center;
        }}
        .chart img {{
            max-width: 100%;
            height: auto;
        }}
    </style>
</head>
<body>
{html_content}
"""

    # Add embedded figures if provided
    if figures:
        html += "\n<h2>Visualizations</h2>\n"
        for name, fig in figures.items():
            img_b64 = figure_to_base64(fig)
            if img_b64:
                html += '<div class="chart">\n'
                html += f"<h3>{name}</h3>\n"
                html += f'<img src="data:image/png;base64,{img_b64}" alt="{name}">\n'
                html += "</div>\n"

    html += """
</body>
</html>
"""

    return html
