[theme]
base = "dark"
primaryColor = "#4da6ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
